server:
  port: 8080
spring:
  application:
    name: blog-web
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${blog.ip}:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: 
    password: 
  data:
    redis:
      host: ${blog.ip}
      # 端口
      port: 6379
      # 指定使用Redis的哪个数据库，Redis服务启动后默认有16个数据库，编号分别是从0到15
      database: 0
      lettuce:
        pool:
          max-active: 8 # 最大连接
          max-idle: 8 # 最大空闲连接
          min-idle: 0 # 最小空闲连接
          max-wait: 1000 # 连接等待时间
      password:  Yp3Zb65D3f7tP6KB

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yyjy.domain.entity
  configuration:
    map-underscore-to-camel-case: true
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  global-config:
    db-config:
      logic-delete-field: delFlag  # 逻辑删除字段名（数据库中的列名）
      logic-delete-value: 1        # 逻辑已删除时字段的值
      logic-not-delete-value: 0    # 逻辑未删除时字段的值
      id-type: auto
      update-strategy: not_null
logging:
  level:
    comment:
      wall:
        mapper: debug
        service: info
        controller: info

springdoc:
  # 默认是false，需要设置为true
  default-flat-param-object: true

minio:
  endpoint: http://${blog.ip}:9000
  access-key: 
  secret-key: 
  bucket: 
